name: Wallace McLeod
favicon: null
layout_spectrum: 1
typography_spectrum: 0.8269
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e4e4e4'
    - '#a8a9ad'
    - '#363e41'
    - '#617888'
    - '#765d1a'
  brandStrength: 0
  lightness: 0.5
  saturation: 0
  rhythmicContrast: 0
purpose: []
